enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 1w

npmScopes:
  midnight-ntwrk:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://npm.nocturne.cash"
    npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.17.1.cjs
